# Generated by Django 5.0.1 on 2024-01-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('lineons', models.BooleanField()),
                ('language', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
            ],
        ),
    ]
